### ISSUE TITLE
VPN Check for IPSEC tunnel is not working

### ISSUE THREAD

**Issue by joke24** [usolved/check_usolved_barracuda_vpn#2]
up and down ipsec vpn transports / tunnels are listed with the same output
active and running vpn-transports:
IPSEC-IPSEC1-192.168.123.0-10.0.0.2

down vpn-transports:
FW2FW-DES01-DES02
IPSEC-IPSEC1Passive-192.168.124.0-10.0.0.3

[nagios] snmpwalk -v2c -c community <firewall-ip> .1.3.6.1.4.1.10704.1.6.1.2
PHION-MIB::vpnState."FW2FW-DES01-DES02" = INTEGER: 0
PHION-MIB::vpnState."IPSEC-IPSEC1-192.168.123.0-10.0.0.2" = INTEGER: 1
PHION-MIB::vpnState."IPSEC-IPSEC1Passive-192.168.124.0-10.0.0.3" = INTEGER: 1

This problem occours on any tested barracuda ng firmware (tested: 5.4, 6.0.5, 6.2.2)
So you can't use this script for ipsec tunnels. 
Only tina-tunnels are working correctly.

I opened a ticket at barracuda to fix this.

**Comment by usolved** [comment]
Thanks for pointing that out. I'll close this issue for now since I can't do anything as long as Barracuda won't fix this bug.

Would be great if you could re-open this issue when you got an answer from Barracuda.

**Comment by joke24** [comment]
barracuda created a bug for that BNNGF-40965

**Comment by joke24** [comment]
Barracuda fixed this partial in 6.2.3
the problem is, you can't differentiate between an admin disabled and down VPN tunnel.
The Barracuda support said, they will not fix this.
So It would be great to modify the script to check the following for IPSEC/Tina:
SNMP return value: 0 or -1 - Tunnel DOWN
SNMP return value: 1 - Tunnel UP

**Comment by usolved** [comment]
Thanks for the info from Barracuda.

Could you explain more in detail what should be changed?
As far as I see, this is already implemented that way.

Starting at this line:
https://github.com/usolved/check_usolved_barracuda_vpn/blob/master/check_usolved_barracuda_vpn.py#L198

I check for state 0 (down disabled), -1 (down) and 1 (active).
